### ISSUE TITLE
Uporządkowanie gałęzi

### ISSUE THREAD

**Issue by andrzejwp** [Budyn/209185#1]
gałąź lab2 zaweria foldery zadanie1, zadanie2. Byłoby prościej, gdyby pliki cpp / hpp umieścił Pan w folderach np. inc / src, a zawartość tych folderów podlegałaby branchowaniu. W przypadku gdy ma Pan wszystko w osobnych folderach i co tydzień kopiuje Pan pliki z poprzedniego zadania do nowego zadania nie ma szczególnej korzyści z zastosowania gałęzi

**Comment by Budyn** [comment]
Zmieniono porządek.
